### ISSUE TITLE
[Apache] prepare proposal

### ISSUE THREAD

**Issue by dailidong** [InterestingLab/seatunnel#685]
Feature Description
Proposal guide:
http://incubator.apache.org/guides/proposal.html

Historical proposals:
https://cwiki.apache.org/confluence/display/INCUBATOR/Proposals

proposal address:
https://docs.google.com/document/d/15pgBLQiaWqMbW34p-_1EA_heiMEXmUnRxb8eqZStQLU/edit?usp=sharing

**Comment by CalvinKirs** [comment]
SeaTunnel Proposal
Abstract
SeaTunnel is a distributed, high-performance data integration platform for the synchronization and transformation of massive data (offline & real-time). SeaTunnel was originally called Waterdrop and was renamed SeaTunnel on October 12, 2021.

Proposal
The goal of the proposal is to incorporate the existing SeaTunnel code repository, developers, and communities into the Apache Software Foundation (ASF) to build a global, diversified and autonomous open-source community in the field of big data synchronization.



Willem Jiang is submitting this proposal to donate SeaTunnel source code and related work(documents, website content, wikis, etc.) to the Apache Software Foundation incubator under the Apache License Version 2.0.

These works are currently available on GitHub at: https://github.com/InterestingLab/SeaTunnel Code repository https://github.com/InterestingLab/SeaTunnel-docs Document repository https://github.com/InterestingLab/ SeaTunnel-example case

Background
In the era of big data, with the emergence of excellent projects such as Apache Spark, Apache Flink, Apache Hadoop, and Apache Kafka, data processing capabilities are rapidly increasing.

However, it is difficult to solve the following problems encountered in massive data synchronization:

Data loss and duplication
Task accumulation and delay
Low throughput
Lack of application running status monitoring
Complex re-development and expansion
Based on this, teams designed and open sourced SeaTunnel in 2017 to provide a good solution to the above issues. At present, SeaTunnel has been adopted in the production environment of many companies and has won wide recognition and admiration by users.

Rationale
The whole processing flow of SeaTunnel can be summarized as  InPut->Filter->Output and constitutes the processing flow of SeaTunnel (Pipeline). We only need to write a SeaTunnel configuration file to complete the data reading, processing, and writing. Input-Output defines the input and output of the data source, and in the Filter, we configure a series of conversions, and most of the data analysis needs are completed in the Filter. SeaTunnel provides a wealth of plug-ins to meet users' needs of real-time & offline synchronization of massive data in different scenarios. At the same time, due to the micro-kernel plug-in architecture, users can easily expand and re-develop based on it.

Current Status
Meritocracy
SeaTunnel was founded in 2017 and was open sourced on GitHub on July 30 of the same year. The project now has contributors and users from more than a dozen companies.

Community
SeaTunnel has been devoting itself to building an active community since it was open-sourced. In four years, we have organized multiple forms of meetups and harvested contributors group from coders, operators (LiFeng) to evangelists. Currently, we have a user base of more than 2,000, and afterward, we will turn to mail and other communication methods that are more in line with the Apache Way to better develop our project.

We hope to expand the contributor group by inviting all friends who follow the Apache Way to contribute. Now, we use GitHub as the code hosting and will use Slack Channel for community communication.

SeaTunnel will welcome more developers and user communities during the incubation period.

Core Developers
Core developers of SeaTunnel include experienced open-source developers and team leaders, and they have formed a diverse team.

Known Risks
Orphaned products
The contributors and community cooperation bring the project from a small concept into a real data processing tool. SeaTunnel has also been widely adopted by companies in China, among which some large companies (ByteDance, Weibo, yixia）have used it extensively in their production. To take the use case of ByteDance as an example, the data set that SeaTunnel synchronizes every day has exceeded 30 billion, and two of the initial committer team will devote themselves full-time to this project.

There are 32 versions of SeaTunnel, which mainly contain 2 major versions. SeaTunnel now has more than ten contributors and thousands of forks, which further shows that it is an active project. We plan to further expand and enrich the community with the aid of Apache. As a consequence, SeaTunnel is unlikely to be reduced to an orphaned project.

Inexperience with Open Source
The initial committer, Calvin Kirs is a PMC member of Apache DolphinScheduler. He participated in the entire process of DolphinScheduler's’ incubation to graduation from Apache and has a deep understanding of Apache release and Apache Way at the same time. Jiajie Zhong is a Committer member of Apache Airflow. Other members also have multiple years of experience in open-source projects, and we will continue to learn the way of Apache during the incubating process to gain more open-source skills. Therefore, we believe that we are experienced enough to operate a well-run community.

Homogenous Developers
Now, the core developers are working in ByteDance, Tencent, WhaleOps, and other companies, and some individual developers are also accepted as SeaTunnel developers. Considering that there are still many users showing great interest in SeaTunnel, we are encouraging and inviting them to be contributors to promote the development of the project.

Reliance on Salaried Developers
Some members of the committer team are paid by their employers to contribute to the project. SeaTunnel itself and massive data synchronization are very attractive and important to the companies that the contributors work for, which will promote better development of the community. Hence, as new contributors continue to emerge, we will work hard to increase diversity.

Relationships with Other Apache Products
Apache DolphinScheduler has supports SeaTunnel as one of the task plugins.

We have integrated with Apache Spark, Apache Flink, and Apache Commons, and plan to do better ecological integration with other Apache projects in the future (Mainly big data projects).

An Excessive Fascination with the Apache Brand
We believe that the Apache brand will bring greater value and reputation to SeaTunnel. However, it is the community provided by the Apache Software Foundation that we hope will enable the project to achieve long-term stable development. Therefore, SeaTunnel proposes incubation in Apache to help diversify the community instead of taking advantage of the Apache brand.

Documentation
A complete set of documents is provided on GitHub, including English and Simplified Chinese versions.

English
Chinese
Initial Code repository
The project consists of three different code repositories, and each of them already exists as a separate git repository.

https://github.com/InterestingLab/seatunnel Code
https://github.com/InterestingLab/seatunnel-docs Documentation repository
https://github.com/InterestingLab/seatunnel-example Development Tutorial
Initial Source
SeaTunnel was first developed in Leshi Internet Information and Technology Corp. Once SeaTunnel is approved to join the Apache incubator, Leshi will provide a Software License Agreement (SGA), and the initial submitter will submit ICLA. This code has been licensed under the Apache Software License, Version 2.0.

Source and Intellectual Property Submission Plan
All dependencies are in compliance with the Apache compatible license, the details are as follows:

External Dependencies
Apache-2.0 licenses

Spark
Flink
Parquet
Phoenix
Apache-commons
HBase-connectors
ElasticSearch (6.3.1) 
elasticsearch-spark(6.8.3)
Fastjson
clickhouse-jdbc
org.lz4:lz4-java
net.jpountz.lz4:lz4
com.101tec:zkclient
com.norbitltd:spoiwo
MIT licenses
slf4j
play-mailer
com.github.scopt(3.7.1)
 

Required Resources
Git Repositories
https://github.com/apache/incubator-seatunnel
https://github.com/apache/incubator-seatunnel-website
https://github.com/apache/incubator-seatunnel-example
Issue Tracking
The community would like to continue using GitHub Issues.

Continuous Integration tool
Travis CI

Mailing Lists
seatunnel-dev：for development discussions
seatunnel-private：for PPMC discussions
seatunnel-notifications：for users notifications
Initial Committers
Gary Gao （garygaowork@gmail.com）
RickyHuo （rickyhuo1994@gmail.com）
kid-xiong （ridxiong@gmail.com）
Calvin Kirs (kirs@apache.org)
Jiajie Zhong (zhongjiajie@apache.org)
Lifeng Nie (Nielifeng@gmail.com)
Affiliations
ByteDance: Gary Gao
Tencent: RickyHuo,kid-xiong
WhaleOps: Calvin Kirs, Jiajie Zhong, LiFeng Nie. 
Sponsors
Champion
Willem Ning Jiang （ningjiang@apache.org ）
Mentors
David Dai (lidongdai@apache.org)
Ted Liu (tedliu@apache.org)
William Guo(guowei@apache.org)
Zhenxu Ke (kezhenxu94@apache.org)
Sponsoring Entity
We are expecting the Apache Incubator could sponsor this project.

**Comment by WillemJiang** [comment]
Just have some quick questions about this project.
1. Do we have website to host the information about the seatunnel?
2. We need to introduce the code history of the seatunnel for signing the SGA.
3. There are some format issues in this proposal need to be address.  ( We can fix it when moving the proposal to ASF incubating wiki)

**Comment by CalvinKirs** [comment]
> Just have some quick questions about this project.
> 
> 1. Do we have website to host the information about the seatunnel?
> 2. We need to introduce the code history of the seatunnel for signing the SGA.
> 3. There are some format issues in this proposal need to be address.  ( We can fix it when moving the proposal to ASF incubating wiki)

Thanks for your review
1: We currently only have a documented website.
2: I revised the `Initial Source` again, please check again.
3: I modified the format, but because the wiki and GitHub formats are not compatible, you can view it on Goog Docs( https://docs.google.com/document/d/15pgBLQiaWqMbW34p-_1EA_heiMEXmUnRxb8eqZStQLU/edit?usp=sharing )

**Comment by CalvinKirs** [comment]
The final version is subject to Google Docs（https://docs.google.com/document/d/15pgBLQiaWqMbW34p-_1EA_heiMEXmUnRxb8eqZStQLU/edit?usp=sharing ）.

**Comment by dailidong** [comment]
I will close this issue because SeaTunnel had been entered into the Apache Incubator Successfully

**Comment by dailidong** [comment]
Thanks to the community, thanks to everyone.
